import { Router } from 'express'; import { prisma } from '../utils/prisma.js'; import { authenticate,allow } from '../middleware/auth.js'; import { AppError } from '../utils/errors.js'; import { AgentAssignmentService } from '../services/agent-assignment.service.js'; import { StatusService } from '../services/status.service.js'; import { OrderStatus } from '@prisma/client';
const r=Router();const assignment=new AgentAssignmentService(),status=new StatusService();r.use(authenticate,allow('ADMIN'));
r.get('/dashboard',async(_q,s)=>{const [total,byStatus,agents]=await Promise.all([prisma.order.count(),prisma.order.groupBy({by:['status'],_count:true}),prisma.deliveryAgent.groupBy({by:['availability'],_count:true})]);s.json({success:true,data:{totalOrders:total,byStatus,agents}})});
r.get('/orders',async(q,s)=>{const where:any={};if(q.query.status)where.status=q.query.status;if(q.query.orderNumber)where.orderNumber={contains:String(q.query.orderNumber),mode:'insensitive'};s.json({success:true,data:await prisma.order.findMany({where,include:{customer:{include:{user:{select:{name:true,email:true}}}},assignedAgent:{include:{user:{select:{name:true}}}}},orderBy:{createdAt:'desc'}})})});
r.get('/customers',async(_q,s)=>s.json({success:true,data:await prisma.customerProfile.findMany({include:{user:{select:{id:true,name:true,email:true,phone:true}},_count:{select:{orders:true}}}})}));
r.get('/agents',async(_q,s)=>s.json({success:true,data:await prisma.deliveryAgent.findMany({include:{user:{select:{name:true,email:true,phone:true}},currentZone:true,_count:{select:{orders:true}}}})}));
r.post('/agents',async(q,s,n)=>{try{const b=q.body;if(await prisma.user.findUnique({where:{email:b.email}}))throw new AppError(409,'Email already registered');const bcrypt=(await import('bcrypt')).default;const u=await prisma.user.create({data:{name:b.name,email:b.email,phone:b.phone,passwordHash:await bcrypt.hash(b.password||'Agent@123',12),role:'AGENT',agent:{create:{availability:b.availability||'OFFLINE',currentZoneId:b.currentZoneId}}}});s.status(201).json({success:true,data:u})}catch(e){n(e)}});
r.patch('/agents/:id',async(q,s)=>s.json({success:true,data:await prisma.deliveryAgent.update({where:{id:q.params.id},data:q.body})}));
r.post('/orders/:id/assign',async(q,s,n)=>{try{s.json({success:true,data:await assignment.assign(q.params.id,q.body.agentId,q.auth!.id)})}catch(e){n(e)}});
r.post('/orders/:id/auto-assign',async(q,s,n)=>{try{s.json({success:true,data:await assignment.autoAssign(q.params.id,q.auth!.id)})}catch(e){n(e)}});
r.patch('/orders/:id/status',async(q,s,n)=>{try{if(!q.body.reason)throw new AppError(422,'A reason is required for admin overrides');s.json({success:true,data:await status.change(q.params.id,q.body.status,q.auth!,q.body.reason,true)})}catch(e){n(e)}});
for(const [name,model] of [['zones','zone'],['areas','area'],['rates','rateCard']] as const){r.get('/'+name,async(_q,s)=>s.json({success:true,data:await (prisma as any)[model].findMany({include:model==='area'?{zone:true}:undefined})}));r.post('/'+name,async(q,s)=>s.status(201).json({success:true,data:await (prisma as any)[model].create({data:q.body})}));r.patch('/'+name+'/:id',async(q,s)=>s.json({success:true,data:await (prisma as any)[model].update({where:{id:q.params.id},data:q.body})}));}
r.get('/cod',async(_q,s)=>s.json({success:true,data:await prisma.codSurcharge.findMany()}));r.patch('/cod/:id',async(q,s)=>s.json({success:true,data:await prisma.codSurcharge.update({where:{id:q.params.id},data:q.body})}));export default r;
